config/routes.rb
Rails.application.routes.draw do

 devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :public do
    root to: 'homes#top'
    get 'posts/list' => 'posts#list',as: 'list'
    resources :posts do
      resources :post_comments,only:[:create, :destroy]
    end
    get 'users/my_page' => 'users#show',as: 'my_page'
    get 'users/ragistration_edit' => 'users#edit',as: 'user_edit'
    patch 'users/ragistration_edit' => 'users#update',as: 'user_update'
    get 'users/confirm' => 'users#confirm',as: 'confirm'
    patch 'users/secession' => 'users#secession',as: 'secession'
    resources :contacts, only:[:new, :create]
  end

  namespace :admin do
    root to: 'posts#top'
    resources :users,only:[:index, :edit, :update]
    resources :maps,only:[:index]
    resources :posts, only:[:index, :show, :update, :destroy] do
      member do
        get 'list'
      end
    end
  end

end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :post, dependent: :destroy
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode

end

app/controllers/admin/maps_controller.rb
class Admin::MapsController < ApplicationController
  def index
    @maps = Map.all
    if params[:id].present?
    @post = Post.find(params[:id])
    end
  end
end

app/helpers/admin/maps_helper.rb
module Admin::MapsHelper
end

app/views/admin/maps/index.html.erb
<label class="mt-4 mb-4 lead"><strong>投稿箇所一覧地図</strong> ※マーカーをクリックすると詳細ページへリンクします</label>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<script>
  let map

    function initMap(){
      geocoder = new google.maps.Geocoder()

      map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 35.68123620000001, lng:139.7671248},
          zoom: 12,
      });


      <% @maps.each do |m| %>
          (function(){
          var latlng = new google.maps.LatLng(<%= m.latitude %>,<%= m.longitude %>);
          var contentString = "住所：<%= m.address %>";

          var marker = new google.maps.Marker({
              position:{lat: <%= m.latitude %>, lng: <%= m.longitude %>},
              map: map,
              title: contentString
          });

          var infowindow = new google.maps.InfoWindow({
            position: latlng,
            content: "<a href='<%= m.post.present? ? admin_post_url(m.post.id): "" %> 'data-turbolinks'= false><%= m.address %></a>"
          }); //ここで詳細ページへのリンクを表示させる
          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });

          })();
      <% end %>
      }
</script>
<script
  src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_KEY'] %>&callback=initMap"
  async defer>
</script>