config/routes.rb
Rails.application.routes.draw do

 devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :public do
    root to: 'homes#top'
    get 'posts/list' => 'posts#list',as: 'list'
    resources :posts do
      resources :post_comments,only:[:create, :destroy]
    end
    get 'users/my_page' => 'users#show',as: 'my_page'
    get 'users/ragistration_edit' => 'users#edit',as: 'user_edit'
    patch 'users/ragistration_edit' => 'users#update',as: 'user_update'
    get 'users/confirm' => 'users#confirm',as: 'confirm'
    patch 'users/secession' => 'users#secession',as: 'secession'
    resources :contacts, only:[:new, :create]
  end

  namespace :admin do
    root to: 'posts#top'
    resources :users,only:[:index, :edit, :update]
    resources :maps,only:[:index]
    resources :posts, only:[:index, :show, :update, :destroy] do
      member do
        get 'list'
      end
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_one :map,dependent: :destroy
  has_many :post_comments, dependent: :destroy
  accepts_nested_attributes_for :map
  validates :post_name, presence: true
  validates :introduction, presence: true
  validates :road_name, presence: true
  validates :image, presence: true
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def top
    @posts = Post.page(params[:page])
  end

  def index
    @posts = Post.page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @map = @post.map
  end

  def list
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_root_path
    else
      render :show
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_root_path
  end

  private
  def post_params
    params.require(:post).permit(:is_active)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container">
  <label class="mt-4 mb-4 lead lead-font-size bg-secondary text-light">事業化候補一覧画面</label>
  <div class="row">
    <table class="table border">
      <thead>
        <tr class="table-primary">
          <th>投稿日時</th>
          <th>投稿名</th>
          <th>投稿者</th>
          <th>コメント数</th>
        </tr>
      </thead>
      <% @posts.each do |post| %>
        <% if post.is_active == true %>
        <tbody>
          <tr>
            <td>
              <%= link_to admin_post_path(post.id) do %>
              <%= l post.created_at %>
              <% end %>
            </td>
            <td><%= post.post_name %></td>
            <td><%= post.user.name %></td>
            <td><%= "#{post.post_comments.count}件" %></td>
          </tr>
        </tbody>
        <% end %>
      <% end %>
    </table>
    <%= paginate @posts %>
  </div>
</div>

app/views/admin/posts/list.html.erb
<div class="container">
  <label class="mt-4 mb-4 lead lead-font-size bg-secondary text-light"><%= @user.name %>さんの投稿一覧</label>
  <div class="row">
    <table class="table border">
      <thead>
        <tr class="table-primary">
          <th>投稿日時</th>
          <th>投稿名</th>
          <th>事業化ステータス</th>
          <th>コメント数</th>
        </tr>
      </thead>
      <tbody>
        <% @posts.each do |post| %>
        <tr>
          <td>
            <%= link_to admin_post_path(post.id), 'data-turbolinks': false do %>
            <%= l post.created_at %>
            <% end %>
          </td>
          <td><%= post.post_name %></td>
          <td>
            <% if post.is_active == true %>
            <label class="text-danger">事業化候補</label>
            <% else %>
            保留
            <% end %>
          </td>
          <td><%= "#{post.post_comments.count}件" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @posts %>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <%= render 'public/posts/show', post: @post, map: @map %>
  <div class="row">
    <div class="col-md-2"></div>
    <%= form_with model: @post,url: admin_post_path do |f| %>
    <div class="col-md-6">
      <label>事業化ステータス</label>
      <div class="mb-3"><%= f.radio_button :is_active, "false",checked: true %>保留   <%= f.radio_button :is_active, "true" %>事業化候補</div>
      <%= f.submit "変更を保存",class: "btn btn-success" %>
      <% end %>
      <%= link_to admin_post_path(@post.id),class: "btn btn-danger",method: :delete, "data-confirm" => "本当に削除しますか？" do %>
        投稿を削除
      <% end %>
      <p>コメント件数：<%= @post.post_comments.count %></p>
      <% @post.post_comments.each do |post_comment| %>
        <p>
          <%= l post_comment.created_at, format: :short %><%= post_comment.user.name %><br>
          <%= post_comment.comment %>
          <%= link_to post_post_comment_path(post_comment.post, post_comment),method: :delete do %>
            コメントを削除
          <% end %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/posts/top.html.erb
<div class="container">
  <label class="mt-4 mb-4 lead lead-font-size bg-secondary text-light">投稿一覧画面</label>
  <div class="row">
    <label class="mb-2">
    <%= link_to admin_posts_path,class: "btn btn-primary" do %>
      事業化候補一覧へ
    <% end %>
    </label>
    <table class="table border">
      <thead>
        <tr class="table-primary">
          <th>投稿日時</th>
          <th>投稿名</th>
          <th>投稿者</th>
          <th>事業化ステータス</th>
          <th>コメント数</th>
        </tr>
      </thead>
      <tbody>
        <% @search_posts.each do |post| %>
        <tr>
          <td>
            <%= link_to admin_post_path(post.id), 'data-turbolinks': false do %>
            <%= l post.created_at %>
            <% end %>
          </td>
          <td><%= post.post_name %></td>
          <td><%= post.user.name %></td>
          <td>
            <% if post.is_active == true %>
              <label class="text-danger">事業化候補</label>
            <% else %>
              保留
            <% end %>
          </td>
          <td><%= "#{post.post_comments.count}件" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @posts %>
  </div>
</div>