config/routes.rb
Rails.application.routes.draw do

 devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :public do
    root to: 'homes#top'
    get 'posts/list' => 'posts#list',as: 'list'
    resources :posts do
      resources :post_comments,only:[:create, :destroy]
    end
    get 'users/my_page' => 'users#show',as: 'my_page'
    get 'users/ragistration_edit' => 'users#edit',as: 'user_edit'
    patch 'users/ragistration_edit' => 'users#update',as: 'user_update'
    get 'users/confirm' => 'users#confirm',as: 'confirm'
    patch 'users/secession' => 'users#secession',as: 'secession'
    resources :contacts, only:[:new, :create]
  end

  namespace :admin do
    root to: 'posts#top'
    resources :users,only:[:index, :edit, :update]
    resources :maps,only:[:index]
    resources :posts, only:[:index, :show, :update, :destroy] do
      member do
        get 'list'
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  validates :name, presence: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <label class="mt-4 mb-4 lead lead-font-size bg-secondary text-light"><%= @user.name %>さんの会員情報編集画面</label>
      <%= form_with model: @user,url: admin_user_path,method: :patch do |f| %>
        <div class="form-group mb-3">
          <label>氏名</label>
          <%= f.text_field:name %>
        </div>
        <div class="form-group mb-3">
          <label>メールアドレス</label>
          <%= f.text_field:email %>
        </div>
        <div class="form-group mb-3">
          <label>会員ステータス</label>
          <%= f.radio_button:is_deleted,"false", checked: true %>有効  <%= f.radio_button:is_deleted,"true" %>退会
        </div>
        <%= f.submit "変更を保存する", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <label class="mt-4 mb-4 lead lead-font-size bg-secondary text-light">会員一覧画面</label>
  <div class="row">
    <table class="table border">
      <thead>
        <tr class="table-primary">
          <th>会員ＩＤ</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
            <% if user.is_deleted == true %>
              <label class="text-danger">退会</label>
            <% else %>
              有効
            <% end %>
          </td>
          <td>
            <%= link_to edit_admin_user_path(user.id),class: "btn btn-success" do %>
              編集する
            <% end %>
          </td>
          <td>
            <%= link_to list_admin_post_path(user.id),class: "btn btn-primary" do %>
              投稿を見る
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <%= paginate @users %>
  </div>
</div>