config/routes.rb
Rails.application.routes.draw do

 devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  scope module: :public do
    root to: 'homes#top'
    get 'posts/list' => 'posts#list',as: 'list'
    resources :posts do
      resources :post_comments,only:[:create, :destroy]
    end
    get 'users/my_page' => 'users#show',as: 'my_page'
    get 'users/ragistration_edit' => 'users#edit',as: 'user_edit'
    patch 'users/ragistration_edit' => 'users#update',as: 'user_update'
    get 'users/confirm' => 'users#confirm',as: 'confirm'
    patch 'users/secession' => 'users#secession',as: 'secession'
    resources :contacts, only:[:new, :create]
  end

  namespace :admin do
    root to: 'posts#top'
    resources :users,only:[:index, :edit, :update]
    resources :maps,only:[:index]
    resources :posts, only:[:index, :show, :update, :destroy] do
      member do
        get 'list'
      end
    end
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
  belongs_to :post, dependent: :destroy
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode

end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_one :map,dependent: :destroy
  has_many :post_comments, dependent: :destroy
  accepts_nested_attributes_for :map
  validates :post_name, presence: true
  validates :introduction, presence: true
  validates :road_name, presence: true
  validates :image, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :comment, presence: true
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :post
  geocoded_by :address
  after_validation :geocode
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  validates :name, presence: true
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/maps_controller.rb
class Admin::MapsController < ApplicationController
  def index
    @maps = Map.all
    if params[:id].present?
    @post = Post.find(params[:id])
    end
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def top
    @posts = Post.page(params[:page])
  end

  def index
    @posts = Post.page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @map = @post.map
  end

  def list
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_root_path
    else
      render :show
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_root_path
  end

  private
  def post_params
    params.require(:post).permit(:is_active)
  end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.page(params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_search

  def set_search
    @search = Post.ransack(params[:q])
    @search_posts = @search.result.page(params[:page])
  end
end

app/helpers/admin/maps_helper.rb
module Admin::MapsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoadReport</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= include_gon %>

    <!--<%= stylesheet_link_tag 'application', media: 'all' %>-->
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <div class="navbar-brand p-3">
              <%= link_to root_path do %>
                Road Report
              <% end %>
            </div>
          <div class="row">
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to admin_root_path ,class: "btn btn-default" do %>
                    投稿一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to admin_users_path ,class: "btn btn-default" do %>
                    会員一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to admin_maps_path ,class: "btn btn-default" do %>
                    地図
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_admin_session_path, method: :delete ,class: "btn btn-default" do %>
                    ログアウト
                  <% end %>
                </li>
              <% elsif user_signed_in? %>
                 <li class="nav-item">
                  <%= link_to my_page_path ,class: "btn btn-default" do %>
                    マイページ
                  <% end %>
                </li>
                 <li class="nav-item">
                  <%= link_to new_post_path ,class: "btn btn-default" do %>
                    投稿する
                  <% end %>
                </li>
                 <li class="nav-item">
                  <%= link_to posts_path ,class: "btn btn-default" do %>
                    投稿一覧
                  <% end %>
                </li>
                 <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete ,class: "btn btn-default" do %>
                    ログアウト
                  <% end %>
                </li>
              <% else %>
               <li class="nav-item">
                  <%= link_to posts_path,class: "btn btn-default" do %>
                    投稿一覧
                  <% end %>
                </li>
               <li class="nav-item">
                  <%= link_to new_user_registration_path ,class: "btn btn-default" do %>
                    新規登録
                  <% end %>
                </li>
               <li class="nav-item">
                  <%= link_to new_user_session_path ,class: "btn btn-default" do %>
                    ログイン
                  <% end %>
                </li>
              <% end %>
              </ul>
            </div>
            <div class="search-box">
              <% if admin_signed_in? %>
                <%= search_form_for @search, url: admin_root_path do |f| %>
                  <%= f.text_field :post_name_cont, placeholder: "投稿名を入力" %>
                  <%= f.submit "検索", class: "search-btn" %>
                <% end %>
              <% else %>
                <%= search_form_for @search, url: posts_path do |f| %>
                  <%= f.text_field :post_name_cont, placeholder: "投稿名を入力" %>
                  <%= f.submit "検索", class: "search-btn" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>

</html>